hero/users/urls.py
from django.urls import path

from hero.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lcore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views

from .views import about, base, blog, blog_item, contact, home, pdf, privacy, services, show_pdf, terms

app_name = 'lcore'
urlpatterns = [
    path('about', about, name='about'),
    re_path('article/(?P<pk>\d+)', show_pdf, name='show_pdf'),
    path('base', base, name='base'),
    path('contact', contact, name='contact'),
    path('blog', blog, name='blog'),
    re_path('blog_item/(?P<pk>\d+)', blog_item, name='blog_item'),
    path('home', home, name='home'),
    path('pdf', pdf, name='pdf'),
    path('privacy', privacy, name='privacy'),
    path('services', services, name='services'),
    path('terms', terms, name='terms'),
    ]

hero/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Hero."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

hero/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

hero/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

templates/hero.html
<!-- ======= Hero Section ======= -->
  <section id="hero">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        <div class="carousel-item active" style="background-image: url({% static 'images/slide/slide-1.jpg' %});">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Welcome to <span>Company</span></h2>
              <p>Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
              <div class="text-center"><a href="" class="btn-get-started">Read More</a></div>
            </div>
          </div>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item" style="background-image: url({% static 'images/slide/slide-2.jpg' %});">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Lorem Ipsum Dolor</h2>
              <p>Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
              <div class="text-center"><a href="" class="btn-get-started">Read More</a></div>
            </div>
          </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item" style="background-image: url({% static 'images/slide/slide-3.jpg' %});">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Sequi ea ut et est quaerat</h2>
              <p>Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
              <div class="text-center"><a href="" class="btn-get-started">Read More</a></div>
            </div>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

    </div>
  </section><!-- End Hero -->

templates/home.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- was the index page  -->

<!-- ======= Hero Section ======= -->
  <section id="hero">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        <div class="carousel-item active" style="background-image: url({% static 'images/slide/slide-1.jpg' %});">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>Welcome to <span>{{co_name}}</span></h2>
              <p>The home for automation and ad-hoc systems</p>
              <!--<div class="text-center"><a href="" class="btn-get-started">Read More</a></div>-->
            </div>
          </div>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item" style="background-image: url({% static 'images/slide/slide-2.jpg' %});">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>We do ... Because</h2>
              <p>We believe life can be simpler</p>
              <!--<div class="text-center"><a href="" class="btn-get-started">Read More</a></div>-->
            </div>
          </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item" style="background-image: url({% static 'images/slide/slide-3.jpg' %});">
          <div class="carousel-container">
            <div class="carousel-content animate__animated animate__fadeInUp">
              <h2>What can we do for you?</h2>
              <p>Have a look at our blog</p>
              <div class="text-center"><a href="{% url 'lcore:blog' %}" class="btn-get-started">Goto Blog</a></div>
            </div>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

    </div>
  </section><!-- End Hero -->
  <main id="main">
<!-- ======= About Us Section ======= -->
    <section id="about-us" class="about-us">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About Us</strong></h2>
        </div>

        <div class="row content">
          <div class="col-lg-6" data-aos="fade-right">
            <h2>Because life can be simpler</h2>
            <h3>There is often opportunity to make your (working) life simpler.</h3>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0" data-aos="fade-left">
            <p>
              So often business practices and processes mutate over time, starting from the simple, straight-forward
              becoming increasingly complex and cumbersome. We take an objective look at this -
            </p>
            <ul>
              <li><i class="ri-check-double-line"></i> Can the data you collect be structured to provide more insight and consistency?</li>
              <li><i class="ri-check-double-line"></i> Which of the manual processes can be automated?</li>
              <li><i class="ri-check-double-line"></i> How and where can the processes be streamlined and simplified?</li>
            </ul>
            <p class="font-italic">
              Why am I doing this? Why am I doing it this way?
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Us Section -->
  <!-- ======= Services Section ======= -->
  <section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Services</strong></h2>
        <p>What we offer to simplify your business</p>
      </div>

      <div class="row">
      {% if services%}
        {% for s in services %}
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
          <div class="icon-box iconbox-blue">
            <div class="icon">
              <!--<img src="{{ MEDIA_URL }}{{ s.image_file }}" alt="" style="width:100px;height:100px;">-->
              <img src="{% static s.link %}" alt="" style="width:100px;height:100px;"/>
            </div>
            <h4><a href="">{{s.service}}</a></h4>
            <p>{{ s.descrip }}</p>
          </div>
        </div>
        {% endfor %}
      {% endif %}
      </div>
    </div>
  </section><!-- End Services Section -->
 <!-- ======= Our Clients Section ======= -->
{% if customers%}
    <section id="clients" class="clients">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Clients</h2>
    </div>
    <div class="row no-gutters clients-wrap clearfix" data-aos="fade-up">
{% for c in customers %}
      <div class="col-lg-3 col-md-4 col-6">
        <h4>{{s.service}}</h4>
        <!--<div class="client-logo">
          <img src="assets/img/clients/client-1.png" class="img-fluid" alt="">
        </div> -->
      </div>
{% endfor %}
    </div>
  </div>
</section><!-- End Our Clients Section -->
{% endif %}



  </main><!-- End #main -->
{% endblock content %}